# Default values for kc-auth
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: quay.io/keycloak/keycloak
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Keycloak configuration
keycloak:
  # Admin configuration
  admin:
    # Admin user for Keycloak
    user: admin
    
    # Admin password (will be base64 encoded in secret)
    password: "admin123"
    
    # Admin user secret reference (contains both username and password)
    secret:
      name: kc-auth-admin-secret
      usernameKey: username
      passwordKey: password
  
  # Keycloak realm configuration
  realm: "openshift"
  realmDisplayName: "OpenShift Authentication Realm"
  
  # Predefined roles to create in the realm
  predefinedRoles:
    - name: "user"
      description: "Standard user role with basic permissions"
    - name: "admin" 
      description: "Administrator role with full system access"
    - name: "devops"
      description: "DevOps role with deployment and infrastructure access"
  
  # Application client configuration (for third-party apps to authenticate against Keycloak)
  appClient:
    clientId: "app-integration-client"
    name: "Application Integration Client"
    clientSecret: "app-client-secret"
    redirectUris:
      - "https://myapp.example.com/auth/callback"
      - "https://myapp.example.com/login/callback"
    webOrigins:
      - "https://myapp.example.com"

# Database configuration
database:
  # Database type (postgres, mysql, mariadb, oracle, mssql, h2)
  type: "postgres"
  
  # Database secret containing connection details
  secret:
    name: "pgvector"
    hostKey: "host"                 # Database host
    portKey: "port"                 # Database port  
    dbnameKey: "dbname"            # Database name
    usernameKey: "user"             # Username key from your secret
    passwordKey: "password"         # Password key from your secret

# Service account configuration
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# RBAC configuration
rbac:
  # Create ClusterRole and ClusterRoleBinding for OpenShift OAuth integration
  create: true

podAnnotations: {}

podLabels: {}

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault

service:
  type: ClusterIP
  port: 8080
  managementPort: 9000

# OpenShift Route configuration
route:
  enabled: true
  host: ""  # Leave empty to auto-generate
  annotations: {}
  tls:
    enabled: true
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    certificate: ""
    key: ""
    caCertificate: ""

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  initialDelaySeconds: 300
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 5

readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 5

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Deployment strategy
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

nodeSelector: {}

tolerations: []

affinity: {}

# Additional environment variables
env: []

# Additional volumes
volumes: []

# Additional volume mounts
volumeMounts: []
