{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "keycloak-auth.fullname" . }}
  labels:
    {{- include "keycloak-auth.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "keycloak-auth.selectorLabels" . | nindent 6 }}
  policyTypes:
  {{- if .Values.networkPolicy.ingress.enabled }}
  - Ingress
  {{- end }}
  {{- if .Values.networkPolicy.egress.enabled }}
  - Egress
  {{- end }}
  {{- if .Values.networkPolicy.ingress.enabled }}
  ingress:
  - from:
    {{- if .Values.networkPolicy.ingress.namespaceSelector }}
    - namespaceSelector:
        {{- toYaml .Values.networkPolicy.ingress.namespaceSelector | nindent 8 }}
    {{- end }}
    {{- if .Values.networkPolicy.ingress.podSelector }}
    - podSelector:
        {{- toYaml .Values.networkPolicy.ingress.podSelector | nindent 8 }}
    {{- end }}
    ports:
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 8443
  {{- end }}
  {{- if .Values.networkPolicy.egress.enabled }}
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 6443
  {{- end }}
{{- end }}