{{- if .Values.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "keycloak-auth.fullname" . }}-rbac
  labels:
    {{- include "keycloak-auth.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "keycloak-auth.fullname" . }}-rbac
  labels:
    {{- include "keycloak-auth.labels" . | nindent 4 }}
rules:
- apiGroups: ["oauth.openshift.io"]
  resources: ["oauthclients"]
  verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "keycloak-auth.fullname" . }}-rbac
  labels:
    {{- include "keycloak-auth.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "keycloak-auth.fullname" . }}-rbac
subjects:
- kind: ServiceAccount
  name: {{ include "keycloak-auth.fullname" . }}-rbac
  namespace: {{ .Release.Namespace }}
{{- end }}