{{- if .Values.realm.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak-auth.fullname" . }}-realm-config
  labels:
    {{- include "keycloak-auth.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
data:
  realm.json: |
    {{ include "keycloak-auth.realmConfig" . | nindent 4 }}
{{- end }}