{{- if .Values.route.enabled }}
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "kc-auth.fullname" . }}
  labels:
    {{- include "kc-auth.labels" . | nindent 4 }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "kc-auth.fullname" . }}
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination }}
    {{- if eq .Values.route.tls.termination "edge" }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy }}
    {{- end }}
    {{- if .Values.route.tls.certificate }}
    certificate: {{ .Values.route.tls.certificate }}
    {{- end }}
    {{- if .Values.route.tls.key }}
    key: {{ .Values.route.tls.key }}
    {{- end }}
    {{- if .Values.route.tls.caCertificate }}
    caCertificate: {{ .Values.route.tls.caCertificate }}
    {{- end }}
  {{- end }}
{{- end }}