builds:
  - name: mcp-weather
    containerfile: weather/Containerfile
    context: weather/src
  - name: oracle-sqlcl
    containerfile: oracle-sqlcl/Containerfile
    context: oracle-sqlcl
  - name: github-mcp
    containerfile: github-mcp/Containerfile
    context: github-mcp
