FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY ingestion_pipeline ingestion_pipeline

CMD ["uvicorn", "ingestion_pipeline.main:app", "--host", "0.0.0.0", "--port", "8000"]
